### ISSUE TITLE
请问支持在xib或者在sb上直接拖拽使用吗？

### ISSUE THREAD

**Issue by yangzhixiao** [youngsoft/TangramKit#1]
请问支持在xib或者在sb上直接拖拽使用吗？

**Comment by youngsoft** [comment]
您好！

  这个是可以支持XIB以及SB的，目前的缺点是不能所见即所得，您可以看看我的OC版本里面有几个DEMO是用的和XIB的结合的，但是Swift版本里面我没有用XIB的DEMO。他们的原理以及方式是一样的。

原始邮件
发件人:杨智晓notifications@github.com
收件人:youngsoft/TangramKitTangramKit@noreply.github.com
发送时间:2016年10月30日(周日) 09:45
主题:[youngsoft/TangramKit] 请问支持在xib或者在sb上直接拖拽使用吗？ (#1)

请问支持在xib或者在sb上直接拖拽使用吗？
