### ISSUE TITLE
什么时候支持swift4

### ISSUE THREAD

**Issue by Mosaics** [youngsoft/TangramKit#13]

**Comment by youngsoft** [comment]
目前我这边用XCODE9跑了一下目前的这个库是没有问题的。也就是XCODE9应该是搭载的swift4.0吧。还是您的问题是什么时候支持对iOS11和iPhoneX的支持吗？ 如果是后者的话OC版本已经快提交上线了，然后Swift版本目前还在修改和调试之中。也会尽快上线的。

**Comment by Mosaics** [comment]
你这个库 在xcode9上支持swift3.2；用4的话就有一些语法问题。希望能更新一个分支到支持swiftt4

**Comment by youngsoft** [comment]
您好。最新版本1.1.2已经完成对Swift4的支持。请下载更新。
