### ISSUE TITLE
怎么才能让子View在没有加入父View的情况下更新布局状态

### ISSUE THREAD

**Issue by DuckDeck** [youngsoft/TangramKit#14]

**Comment by DuckDeck** [comment]
在没有加入父View的情况下frame是0，0，0，0

**Comment by youngsoft** [comment]
如果你的视图的约束是不依赖于父视图的话那么你可以调用layoutIfNeed方法来提前进行布局计算从而得到frame值。这样即使没有加入父视图也是可以得到frame值的。但是如果你的约束就是依赖于父视图那么你就必须要加入到父视图后再来调用layoutIfNeed方法。

**Comment by DuckDeck** [comment]
有一个问题，为什么有时候TGLinearLayout用了.wrap会出现撑不起来这种情况。 要么高宽全是0 或者 宽度不对

**Comment by DuckDeck** [comment]
这个，好像是先写布局，再添加到父View才行。不然就会出现那种问题

**Comment by youngsoft** [comment]
应该不会出现这种情况的，您可以加我QQ：156355113  具体和我沟通您遇到的问题。
