### ISSUE TITLE
发现一个很有趣的库和TangramKit结合起来应该很棒

### ISSUE THREAD

**Issue by geGao123** [youngsoft/TangramKit#15]
https://github.com/schibsted/layout,是一个声明式的布局库。可以在xml文件中设置布局。写起来很像android。TangramKit这个库我第一眼看到很亲切（有很多布局方式和android的常用布局很像），然后我在想，作者能否将TangramKit和layout结合起来，然后真的就可以像写android布局那样写ios的布局。

目前sb和xib目前还不是很完善，希望作者大神，能够看看有没有可行性。（本人技术渣渣，想自己扩展，奈何技术有限，手动捂脸）

**Comment by youngsoft** [comment]
很好的想法，其实这件事情我们一直在做。前一段时间我们计划了一个将android的XML布局文件解析为iOS布局的工程，就是一套android的XML布局可以在iOS上使用。目前就是在OC版本：MyLayout中已经开启了一部分，后来因为一些原因给搁浅了。不过我还是会重启这个计划的。

另外在OC版本中的1.5.0中我实现了一套新的栅格布局MyGridLayout。然后这套布局可以用json格式的语法来描述布局信息。您可以参考一下。

至于swift版本的也是在后续的计划当中。
