### ISSUE TITLE
scrollview类型的UI 较缓慢地滑动时候 布局界面 很卡顿

### ISSUE THREAD

**Issue by BetrayalPromise** [youngsoft/TangramKit#18]
估计是由于scrollView的可视区域变动 导致重新布局子视图 导致布局核心重复计算导致 
建议 UI层更改了runloop捕获模式的操作 可以不重复让布局核心重复计算

**Comment by youngsoft** [comment]
您好，不知道您说的卡顿是做了什么操作，因为我这边的DEMO以及例子都没有出现您所说的问题。您可以通过QQ：156355113 联系我来交流具体细节。

**Comment by BetrayalPromise** [comment]
经查明 是我电脑配置较低的缘故 不好意思
