### ISSUE TITLE
相对布局时，设置宽度为.wrap的UILabel，其他视图参照Label的高度设置高度时，高度设置无效

### ISSUE THREAD

**Issue by changelee82** [youngsoft/TangramKit#25]
如下代码，根据label的高度设置view的高度，正确的结果是红色的view尺寸完全等于label的尺寸，但是，实际的结果是view的高度只覆盖了label的第一行。

        let view = UIView()
        rootLayout.addSubview(view)
        
        let label = UILabel()
        rootLayout.addSubview(label)
        
        label.tg_left.equal(10)
        label.tg_width.equal(.wrap).max(100)
        label.tg_height.equal(.wrap)
        
        view.tg_top.equal(label.tg_top)
        view.tg_bottom.equal(label.tg_bottom)
        view.tg_left.equal(label.tg_left)
        view.tg_right.equal(label.tg_right)
        
        label.text = "测试12345660392034323"
        view.backgroundColor = UIColor.red

**Comment by youngsoft** [comment]
您好，您所提的问题已经修复完成，请将版本升级到1.2.0，同时1.2.0还新增加了布局变换以及流式布局的浮动间距的功能。
