### ISSUE TITLE
这个厉害，希望支持swift4+

### ISSUE THREAD

**Issue by wasdzy111** [youngsoft/TangramKit#26]

**Comment by youngsoft** [comment]
我的代码都是在XCODE9中编译通过的，并且库中的代码是支持swift4.0版本的，有可能DEMO是不支持，这个都不是重点，如果你下载下来只需要对DEMO部分进行部分该进应该就可以运行了，所以不知道你所说的需要支持swfit4+是什么意思，或者您能告知目前库中的哪些代码不支持swfit4+的能力。

**Comment by wasdzy111** [comment]
swift 4.2  TGBaseLayout中 兼容性请支持下

**Comment by czwpro** [comment]
+1 swift4.2还未支持

**Comment by youngsoft** [comment]
已经完全支持和兼容Swift4.2了。请下载最新的1.3.1版本。
