### ISSUE TITLE
tg_sizeThatFits结果不准的问题

### ISSUE THREAD

**Issue by huaxinjiayou** [youngsoft/TangramKit#6]
```
<TGLinearLayout>
	<TGLinearLayout>之前的示例代码</TGLinearLayout>
	<UILabel numberOfLines=0></UILabel>
</TGLinearLayout>
```
这种布局情况会出现tg_sizeThatFits结果不准确。

![image](https://cloud.githubusercontent.com/assets/1059680/21470216/9e33d62c-cab9-11e6-8a1b-1ea6b711266f.png)

**Comment by youngsoft** [comment]
这个问题已经在[V1.0.2](https://github.com/youngsoft/TangramKit/releases/tag/1.0.2)中修复

**Comment by liTao-leven** [comment]
![image](https://user-images.githubusercontent.com/17468545/79214061-c1c24400-7e7c-11ea-870d-3526d09faee3.png)
并没有修复.

**Comment by youngsoft** [comment]
您这个问题没有上下文，不好判断问题所在，可以加入群：178573773 来详细讨论 @liTao-leven

**Comment by liTao-leven** [comment]
@youngsoft 
![image](https://user-images.githubusercontent.com/17468545/80693246-4e1f6880-8b05-11ea-9d43-1b9bc5842e42.png)
又一次遇到,这次包含完整的上下文
