### ISSUE TITLE
我原来的项目是用你的MyLayout,现在我想切换到swift语言来开发，这个框架和原来那个Mylayout能共用吗

### ISSUE THREAD

**Issue by disenr** [youngsoft/TangramKit#8]

**Comment by youngsoft** [comment]
您好！ 这个是可以共用的，因为二者的类名，以及UIView的扩展都是不一样的。不过建议你等一两天我会升级TangramKit到1.0.6。新版本做了新能的提升以及编译的速度加快优化。

**Comment by youngsoft** [comment]
您好！新版本1.0.6已经更新到github和cocoapods里面。请更新即可。。。

**Comment by disenr** [comment]
感谢！

发自我的 iPad
